// Generated by ts-to-zod
import { z } from "zod";

import { contentDtoSchema } from "./contentDto.zod.js";
import { resourceLinkSchema } from "./resourceLink.zod.js";
import { statusInfoDtoSchema } from "./statusInfoDto.zod.js";

export const contentsDtoSchema = z.object({
  links: z.record(resourceLinkSchema),
  total: z.number(),
  items: z.array(contentDtoSchema),
  statuses: z.array(statusInfoDtoSchema),
});
